name: .NET

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:

    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Publish
        run: dotnet publish ./LiteDb.Studio.Avalonia/LiteDb.Studio.Avalonia.csproj -o "${{ matrix.target }}-${{ github.ref_name }}" -c Release --runtime "${{ matrix.target }}" --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true /p:EnableCompressionInSingleFile=true /p:DebugType=None /p:DebugSymbols=false
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          path: ./${{ matrix.target }}-${{ github.ref_name }}/
          filename: '${{ matrix.target }}-${{ github.ref_name }}.zip'
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip
